---
- name: install git & maven
  hosts: dev
  become: yes

  tasks:
  - name: Ensure git package is present
    apt:
     name: git
     state: present
     update_cache: yes

  - name: Ensure maven package is present
    apt:
     name: maven
     state: present
     update_cache: yes       

  - name: Clone a github repository
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /usr/share/app-src
     clone: yes
     update: yes

  - name: Maven package create
    command: mvn -f /usr/share/app-src/pom.xml package -DskipTest


- name: install tomcat
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat9 package is present
    apt:
     name: tomcat9
     state: present
     update_cache: yes 

- name: Fetch war file from dev to tmp
  hosts: dev
  become: yes

  tasks:
    - name: Transfer war from dev to prod
      fetch:
       src: /usr/share/app-src/target/hello-1.0.war
       dest: /tmp/
       flat: yes

- name: Copy war file from master to prod
  hosts: prod
  become: yes

  tasks:
    - name: Transfer war from master to prod
      copy:
       src: /tmp/hello-1.0.war
       dest: /var/lib/tomcat9/webapps