---
- name: install git & maven
  hosts: dev
  become: yes

  tasks:
   - name: Ensure git package is present
      apt:
       name: git
       state: present
       update_cache: yes

   - name: Ensure maven package is present
      apt:
       name: maven
       state: present
       update_cache: yes


   - name: Clone a github repository
       git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /usr/share/app-src
        clone: yes
        update: yes

